name: Create Release Archive
on:
  push
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set filename
      id: vars
      run: |
        echo "zip_file_name=drawio-${GITHUB_REF##*/}.zip" >> $GITHUB_OUTPUT
        echo "tar_file_name=drawio-${GITHUB_REF##*/}.tar.gz" >> $GITHUB_OUTPUT
    - uses: actions/checkout@master

    - name: Archive Release (tar.gz)
      uses: thedoctor0/zip-release@main
      with:
        type: 'tar'
        filename: ${{ steps.vars.outputs.tar_file_name }}
        path: drawio
        exclusions: '*.git*'
    - name: Archive Release (zip)
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: ${{ steps.vars.outputs.zip_file_name }}
        path: drawio
        exclusions: '*.git*'
    - name: Generate signature
      run: |
        echo "${{ secrets.NEXTCLOUD_KEY }}" > drawio.key
        export signature=`openssl dgst -sha512 -sign drawio.key ${{ steps.vars.outputs.tar_file_name }} | openssl base64`
        export releaseUrl="https://github.com/jgraph/drawio-nextcloud/releases/download/${GITHUB_REF##*/}/drawio-${GITHUB_REF##*/}.tar.gz"
        echo "${signature}"
        echo "${releaseUrl}"
        curl -X POST -u "user:password" https://apps.nextcloud.com/api/v1/apps/releases -H "Content-Type: application/json" -d '{"download":"https://github.com/jgraph/drawio-nextcloud/releases/download/${GITHUB_REF##*/}/drawio-${GITHUB_REF##*/}.tar.gz", "signature": "${signature}"}'
        
#    - name: Upload Release
#      uses: ncipollo/release-action@v1
#      with:
#        artifacts: ${{ steps.vars.outputs.zip_file_name }},${{ steps.vars.outputs.tar_file_name }}
#        token: ${{ secrets.GITHUB_TOKEN }}
